export { default as BodyMdBold } from './BodyMdBold'
export { default as BodyMd } from './BodyMd'
export { default as HeadingMd } from './HeadingMd'
export { default as HeadingLg } from './HeadingLg'
export { default as HeadingXl } from './HeadingXl'
export { default as HeadingSm } from './HeadingSm'
